---
- name: Download Hadoop
  hosts: all
  tasks:
      - get_url: 
          url: https://archive.apache.org/dist/hadoop/core/hadoop-3.2.0/hadoop-3.2.0.tar.gz
          dest: ~/

- name: Extract Hadoop
  hosts: all
  tasks:
      - unarchive: 
          src: ~/hadoop-3.2.0.tar.gz 
          dest: /usr/local/ 
          owner: root 
          group: root 
          creates: /usr/local/hadoop 
          copy: no
          sudo: yes

      - command: mv /usr/local/hadoop-3.2.0 /usr/local/hadoop creates=/usr/local/hadoop removes=/usr/local/hadoop-3.2.0

      - lineinfile: path=/root/.bashrc line="export HADOOP_HOME=/usr/local/hadoop"
      - lineinfile: path=/root/.bashrc line="export HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop"  
      - lineinfile: path=/root/.bashrc line="export PATH=$PATH:$HADOOP_HOME/bin"

- name: Update the xml files
  hosts: all
  tasks:
      - template: src={{ item.src }} dest={{ item.dest }} owner="root" group="root"
        with_items:
         - {src: "templates/core-site.xml", dest: "/usr/local/hadoop/etc/hadoop/core-site.xml"}
         - {src: "templates/hdfs-site.xml", dest: "/usr/local/hadoop/etc/hadoop/hdfs-site.xml"}
         - {src: "templates/yarn-site.xml", dest: "/usr/local/hadoop/etc/hadoop/yarn-site.xml"}
         - {src: "templates/mapred-site.xml", dest: "/usr/local/hadoop/etc/hadoop/mapred-site.xml"}

- name: Add slaves file
  hosts: MASTER
  tasks: 
       - template: src="templates/slaves" dest="/usr/local/hadoop/etc/hadoop/slaves" owner="root" group="root"

- name: Format HDFS and launch
  hosts: MASTER
  tasks:
    #- shell: . ~/.bashrc
    #- command: hdfs namenode -format
    #- command: $HADOOP_PREFIX/sbin/start-dfs.sh
    #- command: $HADOOP_PREFIX/sbin/start-yarn.sh

