---
- name: Download Hadoop
  hosts: all
  tasks:
      - get_url: 
          url: http://apache.lauf-forum.at/hadoop/common/hadoop-2.9.0/hadoop-2.9.0.tar.gz
          dest: ~/

- name: Extract Hadoop
  hosts: all
  tasks:
      - unarchive: 
          src: ~/hadoop-2.9.0.tar.gz 
          dest: /usr/local/ 
          owner: hadoopuser 
          group: hadoopuser 
          creates: /usr/local/hadoop 
          copy: no

      - command: mv /usr/local/hadoop-2.9.0 /usr/local/hadoop creates=/usr/local/hadoop removes=/usr/local/hadoop-2.9.0

      - lineinfile: path=/hadoopuser/.bashrc line="export HADOOP_HOME=/usr/local/hadoop"
      - lineinfile: path=/hadoopuser/.bashrc line="export HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop"  
      - lineinfile: path=/hadoopuser/.bashrc line="export PATH=$PATH:$HADOOP_HOME/bin"

- name: Update the xml files
  hosts: all
  tasks:
      - template: src={{ item.src }} dest={{ item.dest }} owner="hadoopuser" group="hadoopgroup"
        with_items:
         - {src: "templates/core-site.xml", dest: "/usr/local/hadoop/etc/hadoop/core-site.xml"}
         - {src: "templates/hdfs-site.xml", dest: "/usr/local/hadoop/etc/hadoop/hdfs-site.xml"}
         - {src: "templates/yarn-site.xml", dest: "/usr/local/hadoop/etc/hadoop/yarn-site.xml"}
         - {src: "templates/mapred-site.xml", dest: "/usr/local/hadoop/etc/hadoop/mapred-site.xml"}

- name: Add slaves file
  hosts: MASTER
  tasks: 
       - template: src="templates/slaves" dest="/usr/local/hadoop/etc/hadoop/slaves" owner="hadoopuser" group="hadoopgroup"

- name: Format HDFS and launch
  hosts: MASTER
  tasks:
    #- shell: . ~/.bashrc
    #- command: hdfs namenode -format
    #- command: $HADOOP_PREFIX/sbin/start-dfs.sh
    #- command: $HADOOP_PREFIX/sbin/start-yarn.sh
