---
- name: Configure Java
  hosts: all
  tasks:
      - name: Install jdk for jps
        apt: name=openjdk-8-jdk state=present
        sudo: true

      - name: Install jdk for jps
        apt: name=openjdk-8-source state=present
        sudo: true

      - name: Update environment with Java
        become: yes
        lineinfile:
          path: /etc/environment
          line: 'JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"'
