---
- name: Download Spark
  hosts: MASTER
  become: yes
  tasks:
   - get_url: 
      url: http://artfiles.org/apache.org/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz
      dest: ~/

- name: Extract Spark
  hosts: MASTER
  tasks:
   - unarchive: 
      src: ~/spark-2.4.3-bin-hadoop2.7.tgz
      dest: /usr/local/
      owner: root
      group: root
      creates: /usr/local/spark
      copy: no
   
   - command: mv /usr/local/spark-2.4.3-bin-hadoop2.7 /usr/local/spark creates=/usr/local/spark removes=/usr/local/spark-2.4.3-bin-hadoop2.7
   - lineinfile: path=/root/.bashrc line="export SPARK_HOME=/usr/local/spark"
   - lineinfile: path=/root/.bashrc line="export PATH=$PATH:$SPARK_HOME/bin"

- name: Update spark configuration
  hosts: MASTER
  tasks:
   - template: src="templates/spark-defaults.conf" dest="/usr/local/spark/conf/spark-defaults.conf" owner="root" group="root"

