---
- hosts: MASTER
  tasks:
    - name: generate key pair
      user:
       name: root
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

    - name: test public key
      shell: ssh-keygen -l -f /root/.ssh/id_rsa.pub
      changed_when: false

    - name: retrieve public key
      shell: cat /root/.ssh/id_rsa.pub
      register: master_public_key
      changed_when: false

- hosts: all
  tasks:
    - name: add master public key to slaves
      authorized_key:
        user: root
        key: "{{ hostvars['10.155.208.40'].master_public_key.stdout }}"
